title: CyberInfra
description: "Operating Systems, Computer Networks, CyberSecurity..."
author:
  name: "Luiz Arthur F. Santos"
  email: "luizsantos@utfpr.edu.br / luiz.arthur.feitosa.santos@gmail.com"
#  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  


# Custom variables
owner : "luiz"
company : "CyberInfra"
year : "2020"
